name: Kivy app to Apk
description: Convert Kivy app to APK
branding:
  icon: kivy
  color: green
on:
  workflow-call:
    inputs:
      command:
        id: cmd
        description: 'Buildozer command'
        required: false
        default: 'buildozer -v android debug'
      python-version:
        id: python-ver
        description: 'Python version to use'
        required: false
        default: '3.11.6'
      working-directory:
        id: work-dir
        description: 'Directory that contains main.py'
        default: '.'
        required: True
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        architecture: x64
        python-version: ${{inputs.python-version || inputs.python-ver.default}}

    #changing to working directory
    - name: Setting up Directory
      shell: bash
      run: |
        cd ${{inputs.working-directory || inputs.work-dir.default}}

    #install some dependencies
    - name: Install and upgrade dependencies
      id: dependencies-install
      shell: bash
      run: |
        echo ${{inputs.python-version || inputs.python-ver.default}}
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        sudo apt upgrade
        export PATH=$PATH:~/.local/bin/
        python -m pip install --upgrade \
          Cython==0.29.33 \
          virtualenv \
          kivymd \
          python-for-android \
          xkivy \
          pyjnius \
          buildozer \
          kivymd
            
    #install requirement in requirements.txt
    - name: Install requirements in requirements.txt if it exists
      shell: bash
      if: ${{ hashFiles('requirements.txt') != '' }}
      run: |
        python -m pip install -r requirements.txt

    #build with buildozer
    - name: Build with Buildozer
      id: buildozer
      shell: bash
      run: |
        ${{inputs.command || inputs.cmd.default}}
      
    #upload apk
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: ./bin
