name: Kivy app to Apk
description: Convert Kivy app to APK
branding:
  icon: kivy
  color: green
on:
  workflow-call:
    inputs:
      buildozer-command:
        description: 'Buildozer command'
        required: true
        default: 'buildozer -v android debug'
      python-version:
        description: 'Python version to use'
        required: true
        default: '3.11.6'
      working-directory:
        description: 'Directory that contains main.py'
        default: '.'
        required: true
      runs-on:
        description: 'Platform to run on defaults to ubuntu-latest'
        default: 'ubuntu-latest'
        required: true
runs:
  using: composite
  steps:
    - start:
      id: start
      uses: ./main.yaml
