name: 'Kivy App to APK'
description: 'Convert Kivy app to APK'
inputs:
  python-version:
    description: 'Python version to use'
    default: '3.8'
  workdir:
    default: '.'
    description: 'Working directory'
  buildozer-cmd:
    default: 'buildozer android debug'
    description: 'Buildozer command to use'

runs:
  using: "composite"
  steps:
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        architecture: x64
        python-version: ${{ inputs.python-version }}

    - name: Install and upgrade dependencies
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        python3 -m pip install --upgrade \
          Cython==0.29.33 \
          virtualenv \
          python-for-android \
          buildozer
      shell: bash

    - name: Install requirements in requirements.txt if it exists
      run: |
        if [ -f requirements.txt ]; then
          python3 -m pip install -r requirements.txt
        fi
      shell: bash

    - name: Build with Buildozer
      run: |
        ${{ inputs.buildozer-cmd }}
      shell: bash
