on:
  workflow-call:

jobs:
   starting-buildozer-action:
     runs-on: ${{ steps.step1.inputs.runs-on || 'ubuntu-latest' }}
     defaults:
       run:
         working-directory: ${{ steps.step1.inputs.working-directory || '.' }}
     steps:
       #changing to working directory
       - name: Setting up Directory
         shell: bash
         run: |
           echo $PWD
        
       - uses: actions/checkout@v4
       - name: Setup python
         uses: actions/setup-python@v2
         with:
           architecture: x64
           python-version: ${{ steps.step1.inputs.python-version || '3.11.6' }}

       #install some dependencies
       - name: Install and upgrade dependencies
         shell: bash
         working-directory: ${{ steps.step1.inputs.working-directory || '.' }}
         run: |
           sudo apt update
           sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
           sudo apt upgrade
           export PATH=$PATH:~/.local/bin/
           python -m pip install --upgrade \
             Cython==0.29.33 \
             virtualenv \
             kivymd \
             python-for-android \
             xkivy \
             pyjnius \
             buildozer \
             kivymd
            
       #install requirements in requirements.txt if so
       - name: Install requirements in requirements.txt if it exists
         shell: bash
         working-directory: ${{ steps.step1.inputs.working-directory || '.' }}
         if: ${{ hashFiles('requirements.txt') != '' }}
         run: |
           python -m pip install -r requirements.txt

       #build with buildozer
       - name: Build with Buildozer
         shell: bash
         working-directory: ${{ steps.step1.inputs.working-directory || '.' }}
         run: |
           ${{ inputs.buildozer-command || 'buildozer -v android debug' }}
      
        #upload apk
        - name: Upload artifacts
          uses: actions/upload-artifact@v2
          with:
            name: package
            path: ./bin
